### ISSUE TITLE
Version mismatch 4.2.3 vs 4.3.2

### ISSUE THREAD

**Issue by pazampog** [lhncbc/fhir-obs-viewer#5] opened 2022-04-07 17:16 UTC
Hi All,

I have started using the 4.2.3 version from this repository and following the readme the application is correctly started and I'm able to browse it.
However when I paste the URL of my testing FHIR server (i.e. the [public HAPI FHIR server](https://hapi.fhir.org/baseR4)) I see errors in the browser console highlithing definitions are not properly loaded. Following the source code, I find the problem is here: 
`const definitions = definitionsIndex.configByVersionName[versionName]; ` 
in fhir-backend.service.ts (line 293)

If I try to use the online version (with the same FHIR public server) of the application (URL.: [this]( https://lhcforms.nlm.nih.gov/fhir/research-data-finder/) ) everything works fine.
By the way I noted that the version on this repo is 4.2.3 while that one of the online version is 4.3.2. 
Maybe in 4.3.2 version this kind of problem has been solved? Can you provide me a feedback on how to fix this issue?

Thx

**Comment by plynchnlm** [comment] 2022-04-07 18:34
Thanks for mentioning that.  We've been having intermittent connection issues with GitHub, so some of our updates have not been making it here.  I have pushed them now, so you should see the tag for 4.3.2.

**Comment by pazampog** [comment] 2022-04-07 22:02
Many thanks,

I have started again the application unsing tag 4.3.2 this time. Unfortunately the problem (exactly the same) did not disappear. It seems like the preliminary retrival of "definitions" that should happen at the start does not happen because that variable "definitions"  is undefined (I have debugged using chrome console). Please can you provide a feedback/suggestion about how to initialize correctly such definitions? The guide simply states to execute "npm install" and then "npm start" but maybe some other configuration action is needed?

Thx

**Comment by plynchnlm** [comment] 2022-04-08 16:38
Did you run "npm run build"?

**Comment by pazampog** [comment] 2022-04-08 17:12
Yes...I executed (as you suggested) the "npm run build" but the result is the same. Really the "build" step is performed also by the npm start so there is no difference. I attach here below 3 screens for convenience:
scree_1: shows what I see in browser console when I usa the URL.: "https://lforms-fhir.nlm.nih.gov/baseR4"
scree_2: shows what I see in browser console when I usa the URL.: "https://hapi.fhir.org/baseR4"
scree_3: shows what I see debugging with a breakpoint at line 293 of fhirBackendService (obviously always using the URL: "https://hapi.fhir.org/baseR4")
As you see the screen_1 shows no blocking problem. In screen 2 you can see how and where the error arises and the confirmation is demonstrated with screen_3 where is pointed out that "definitions" is undefined.
<img width="923" alt="screen_1" src="https://user-images.githubusercontent.com/8290423/162489891-cd255475-a978-45ff-aa50-4f895fc18368.png">
<img width="864" alt="screen_2" src="https://user-images.githubusercontent.com/8290423/162489896-aea07b54-97e8-4f8d-93e2-a70822c61d2d.png">
<img width="918" alt="screen_3" src="https://user-images.githubusercontent.com/8290423/162489899-5f6ba254-de6b-4b3c-a387-b79caf3b5cd2.png">

**Comment by plynchnlm** [comment] 2022-04-08 17:32
I see the README says "npm install", but I think it should be "npm ci" in order to get the same versions specified in package-lock.json.  Could you 1) make sure package.json and package-lock.json are not modified, and 2) run "npm ci" to install the packages.

**Comment by plynchnlm** [comment] 2022-04-08 21:26
We could not reproduce the problem even when running "npm install", and using the server you specified.  What value do you have for "versionName" when definitions is undefined at line 296?

**Comment by pazampog** [comment] 2022-04-09 08:31
> What value do you have for "versionName" when definitions is undefined at line 296?

I see 4.3.2

**Comment by pazampog** [comment] 2022-04-09 09:55
Hi,

I repeated the whole process:
1) downloaded again the zip
2) executed the "npm ci" and following the "npm start" (these steps happened without errors, I mean some warning but everything seems ok) - see attached figures (npm_ci.png, npm_start_1.png, npm_start_2.png, npm_start_3.png)
3) when I jump in the browser this time I experienced the following:
setting page, URL= "dbgap..."=> usual problem "definitions" is undefined (see screen dbgap.png)
setting page, URL= "ilform..."=> I don't see the error (see ilforms_setting_no error.png)
BUT if I try to define a cohort (with this ilform URL set) => the rules, within ruleset, at line 234 of search-parameters.component, is undefined and naturally an error arises preventing to go ahead (see ilform_define_criteria.png)
I hope this analysis could help you to find where the problem could be. I have the impression in the online version everthing works fine because there is a pre-loading or in any case a loading mechanism that allows the definitions to be correctly loaded. Maybe, as suggestion, you could try to make a test like a third party user...I mean download the zip in a new folder and repeat the same steps...maybe that in a cleaned and new condition you catch the same problem. Thanks for the support.

<img width="725" alt="npm_ci" src="https://user-images.githubusercontent.com/8290423/162566297-3113b3cc-be29-401e-b3e3-2628964fbcd5.png">
<img width="613" alt="npm_start_1" src="https://user-images.githubusercontent.com/8290423/162566300-284d63a6-ce19-47ad-bc5a-b12b72b9750e.png">
<img width="614" alt="npm_start_2" src="https://user-images.githubusercontent.com/8290423/162566389-cf763f22-6e66-4243-9a55-d40f7897054c.png">
<img width="615" alt="npm_start_3" src="https://user-images.githubusercontent.com/8290423/162566465-fd6e3c86-67da-48f7-a91a-aaa1ceede071.png">
<img width="934" alt="dbgap" src="https://user-images.githubusercontent.com/8290423/162566512-0442e6af-c6fe-4a80-9153-d69d2ba71e65.png">
<img width="929" alt="ilforms_setting_no error" src="https://user-images.githubusercontent.com/8290423/162566521-d17aa0d9-4eb4-4558-9201-d0ff0e117c9e.png">
<img width="923" alt="ilform_define_criteria" src="https://user-images.githubusercontent.com/8290423/162566527-17c8f3b6-57b2-4413-890e-41e9bc633bc6.png">

**Comment by wizard982** [comment] 2022-04-11 10:06
I have this problem too. Please, can you fix?

**Comment by plynchnlm** [comment] 2022-04-11 20:13
Our current theory is that this is a problem on Windows.  In webpack/extra-webpack.config.js,

change
      test: /definitions\/index.json$/,
to
      test: /definitions[\\\/]index.json$/,

We should have a fix with that change out soon.

**Comment by plynchnlm** [comment] 2022-04-11 20:59
This fix is now in 4.3.3.  Closing, optimistically, but feel free to reopen if there are still problems.

**Closed by plynchnlm** 2022-04-11 20:59 UTC

**Comment by pazampog** [comment] 2022-04-15 15:20
> This fix is now in 4.3.3. Closing, optimistically, but feel free to reopen if there are still problems.

Great! Many thanks...
